name: publish

on:
  push:
    branches: [ "master","Scoreboard" ]
  pull_request:
    branches: [ "Scoreboard" ]

jobs:
  publish-UI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd uiredes
        docker image build -t bulan506/contaminados2024ui:latest .
        docker image build -t bulan506/contaminados2024ui:0.0.1 .
        echo "${{ secrets.DOCKERHUBPASSC28223  }}" | docker login -u "brandon.vargassolano@ucr.ac.cr" --password-stdin
        docker push bulan506/contaminados2024ui:latest
        docker push bulan506/contaminados2024ui:0.0.1
